version: "3.9"

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: docker/production/Dockerfile
    env_file:
      - ./.env.production
    ports:
      - "8888:5000"
    networks:
      - queue-net

networks:
  queue-net:
    driver: bridge
